spring.application.name=papelaria-sinclair

# H2 - banco em memoria (para mudar para PostgreSQL/MySQL, substitua as 3 linhas abaixo)
spring.datasource.url=jdbc:h2:mem:papelaria_db;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=papelaria-sinclair-chave-secreta-para-assinar-tokens-jwt-hs256-2024
jwt.expiration=86400000

server.port=8080
